%%
%% Autogenerated by Thrift Compiler (0.9.1)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(include_types).

-include("include_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('includeTest') ->
  {struct, [{1, {struct, {'thriftTest_types', 'bools'}}}]}
;

struct_info('i am a dummy struct') -> undefined.

struct_info_ext('includeTest') ->
  {struct, [{1, required, {struct, {'thriftTest_types', 'bools'}}, 'bools', #bools{}}]}
;

struct_info_ext('i am a dummy struct') -> undefined.

